import type { ContextMap, RepoProfile } from "@axis/context-engine";
import type { GeneratedFile, SourceFile } from "./types.js";

// ─────────────────────────────────────────────────────────────────────────────
// Verify-gate generator.
//
// Emits a stack-aware "only green code gets pushed" gate for the analyzed repo:
//   • verify.sh       — fast pre-push gate (lint + quick tests)
//   • verify-full.sh  — the whole suite (build + full tests) for pre-merge/release
//   • .githooks/pre-push — runs verify.sh on every push (install via core.hooksPath)
//
// Rationale baked into the output: CI is expensive to use as the *iteration*
// loop (push → see failures → fix → push burns CI minutes fast). This flips it —
// iterate locally until green, push green, and CI becomes a confirmation
// backstop. Detection mirrors the file-based idiom other generators use.
// ─────────────────────────────────────────────────────────────────────────────

function hasAny(files: SourceFile[] | undefined, pattern: RegExp): boolean {
  if (!files) return false;
  return files.some((f) => pattern.test(f.path));
}

function detectPackageManager(files?: SourceFile[]): "pnpm" | "yarn" | "npm" {
  if (hasAny(files, /(^|\/)pnpm-lock\.yaml$/)) return "pnpm";
  if (hasAny(files, /(^|\/)yarn\.lock$/)) return "yarn";
  return "npm";
}

interface StackPlan {
  /** Fast gate: lint + quick/changed tests — runs on every push. */
  fast: string[];
  /** Full gate: build + complete test suite — pre-merge / release. */
  full: string[];
}

function planStack(ctx: ContextMap, files?: SourceFile[]): StackPlan {
  const fast: string[] = [];
  const full: string[] = [];
  const fw = ctx.detection.frameworks.map((f) => f.name.toLowerCase());

  const isNode =
    hasAny(files, /(^|\/)package\.json$/) ||
    fw.some((f) => ["react", "next.js", "svelte", "vue", "nuxt", "node.js"].includes(f));
  const isPython = hasAny(files, /(^|\/)pyproject\.toml$|(^|\/)requirements\.txt$|\.py$/);
  const isGo = hasAny(files, /(^|\/)go\.mod$/) || hasAny(files, /\.go$/);
  const isNext = fw.includes("next.js") || hasAny(files, /(^|\/)next\.config\.[tjm]s$/);

  const pm = detectPackageManager(files);
  const run = (s: string) => (pm === "npm" ? `npm run ${s} --if-present` : `${pm} run ${s} --if-present`);
  const exec = (s: string) => (pm === "npm" ? `npx ${s}` : `${pm} exec ${s}`);

  if (isNode) {
    fast.push(run("lint"));
    if (hasAny(files, /(^|\/)tsconfig\.json$/)) fast.push(exec("tsc --noEmit"));
    fast.push(run("test"));
    full.push(run("build"));
    if (isNext && !hasAny(files, /(^|\/)package\.json$/)) full.push(exec("next build"));
    full.push(run("test"));
  }

  if (isPython) {
    if (hasAny(files, /(^|\/)\.?ruff\.toml$/) || hasAny(files, /(^|\/)pyproject\.toml$/)) {
      fast.push("ruff check .");
    }
    fast.push("python -m pytest -q -x");
    full.push("python -m pytest -q");
  }

  if (isGo) {
    fast.push("go vet ./...");
    fast.push("go test ./...");
    full.push("go build ./...");
    full.push("go test ./...");
  }

  if (fast.length === 0) fast.push('echo "No stack detected — customize verify.sh"');
  if (full.length === 0) full.push('echo "No stack detected — customize verify-full.sh"');
  return { fast, full };
}

function renderScript(title: string, intro: string, cmds: string[]): string {
  const head = [
    "#!/usr/bin/env bash",
    `# ${title} — generated by Axis Iliad (stack-aware). Customize as needed.`,
    `# ${intro}`,
    "set -euo pipefail",
    'cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"',
    "",
  ];
  const body = cmds.flatMap((c) => [`echo "→ ${c}"`, `${c} || { echo "✗ ${title} failed: ${c}"; exit 1; }`]);
  return [...head, ...body, "", `echo "✅ ${title} passed"`, ""].join("\n");
}

export function generateVerifyGate(ctx: ContextMap, _profile: RepoProfile, files?: SourceFile[]): GeneratedFile {
  const plan = planStack(ctx, files);
  return {
    path: "verify.sh",
    content: renderScript(
      "verify",
      "Fast pre-push gate — only green code gets pushed (CI becomes a backstop, not the loop).",
      plan.fast,
    ),
    content_type: "text/x-shellscript",
    program: "superpowers",
    description: "Fast pre-push lint + test gate (stack-aware); pairs with .githooks/pre-push",
  };
}

export function generateVerifyFull(ctx: ContextMap, _profile: RepoProfile, files?: SourceFile[]): GeneratedFile {
  const plan = planStack(ctx, files);
  return {
    path: "verify-full.sh",
    content: renderScript(
      "verify-full",
      "Whole-package gate (build + full test suite) — run before merging to main / releasing.",
      plan.full,
    ),
    content_type: "text/x-shellscript",
    program: "superpowers",
    description: "Full build + complete test-suite gate (stack-aware)",
  };
}

export function generatePrePushHook(_ctx: ContextMap, _profile: RepoProfile, _files?: SourceFile[]): GeneratedFile {
  const content = [
    "#!/usr/bin/env bash",
    "# Pre-push gate — only green code gets pushed. Generated by Axis Iliad.",
    "#",
    "# INSTALL (one-time, from the repo root):",
    "#   chmod +x verify.sh verify-full.sh .githooks/pre-push",
    "#   git config core.hooksPath .githooks",
    "#",
    "# Bypass in a genuine emergency with:  git push --no-verify",
    "set -euo pipefail",
    'ROOT="$(git rev-parse --show-toplevel)"',
    'echo "▶ pre-push: running fast verify gate (verify.sh)…"',
    'exec bash "$ROOT/verify.sh"',
    "",
  ].join("\n");
  return {
    path: ".githooks/pre-push",
    content,
    content_type: "text/x-shellscript",
    program: "superpowers",
    description: "Git pre-push hook running verify.sh (install via core.hooksPath .githooks)",
  };
}
