/**
 * Embeddable context snippet for axis-iliad
 * Generated by Axis' Iliad
 * Drop this into any AI prompt to inject project context
 */

export const PROJECT_CONTEXT = {
  name: "axis-iliad",
  type: "monorepo",
  language: "TypeScript",
  description: "> **Axis' Iliad — The modern epic that shapes raw codebases into canonical, agent-ready artifacts. Axis' Iliad authors the definitive foundation for the next era of natural-language workspace development.**",
} as const;

export const CONVENTIONS = [
  "TypeScript strict mode",
  "Linter configured",
  "Formatter configured",
  "Makefile build",
] as const;

export const WARNINGS = [
  "No lockfile found — dependency versions may be inconsistent",
] as const;

export const KEY_ABSTRACTIONS = [
  "apps/ (monorepo_apps)",
  "packages/ (monorepo_packages)",
  "docs/ (documentation)",
  "examples/ (project_directory)",
  "mcp/ (project_directory)",
  ".github/ (project_directory)",
  "algorithmic/ (project_directory)",
  "artifacts/ (project_directory)",
] as const;

/**
 * Inject into an AI prompt as a system-level context block.
 * Usage: embedProjectContext() returns a formatted string.
 */
export function embedProjectContext(): string {
  const sections = [
    `# Project: ${PROJECT_CONTEXT.name}`,
    `Type: ${PROJECT_CONTEXT.type} | Language: ${PROJECT_CONTEXT.language}`,
    `Description: ${PROJECT_CONTEXT.description}`,
    "",
    "## Conventions",
    ...CONVENTIONS.map(c => `- ${c}`),
    "",
    "## Warnings",
    ...WARNINGS.map(w => `- ${w}`),
    "",
    "## Key Abstractions",
    ...KEY_ABSTRACTIONS.map(a => `- ${a}`),
  ];
  return sections.join("\n");
}

export const ENTRY_POINTS = [
  { path: "apps/api/src/server.ts", exports: ["export const app = ..."] },
  { path: "apps/web/src/App.tsx", exports: ["export function App() { ... }"] },
  { path: "apps/web/src/main.tsx", exports: [] },
  { path: "packages/context-engine/src/index.ts", exports: ["export type { ... }","export { ... }"] },
] as const;