#!/usr/bin/env bash
# verify — generated by Axis Iliad (stack-aware). Customize as needed.
# Fast pre-push gate — only green code gets pushed (CI becomes a backstop, not the loop).
set -euo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"

echo "→ pnpm run lint --if-present"
pnpm run lint --if-present || { echo "✗ verify failed: pnpm run lint --if-present"; exit 1; }
echo "→ pnpm exec tsc --noEmit"
pnpm exec tsc --noEmit || { echo "✗ verify failed: pnpm exec tsc --noEmit"; exit 1; }
echo "→ pnpm run test --if-present"
pnpm run test --if-present || { echo "✗ verify failed: pnpm run test --if-present"; exit 1; }

echo "✅ verify passed"
