#!/usr/bin/env bash
# verify — generated by Axis Iliad (stack-aware). Customize as needed.
# Fast pre-push gate — only green code gets pushed (CI becomes a backstop, not the loop).
set -euo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"

echo "→ npm run lint --if-present"
npm run lint --if-present || { echo "✗ verify failed: npm run lint --if-present"; exit 1; }
echo "→ npx tsc --noEmit"
npx tsc --noEmit || { echo "✗ verify failed: npx tsc --noEmit"; exit 1; }
echo "→ npm run test --if-present"
npm run test --if-present || { echo "✗ verify failed: npm run test --if-present"; exit 1; }

echo "✅ verify passed"
