#!/usr/bin/env bash
# verify-full — generated by Axis Iliad (stack-aware). Customize as needed.
# Whole-package gate (build + full test suite) — run before merging to main / releasing.
set -euo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"

echo "→ pnpm run build --if-present"
pnpm run build --if-present || { echo "✗ verify-full failed: pnpm run build --if-present"; exit 1; }
echo "→ pnpm run test --if-present"
pnpm run test --if-present || { echo "✗ verify-full failed: pnpm run test --if-present"; exit 1; }

echo "✅ verify-full passed"
