#!/usr/bin/env node
// iliad — generate and maintain agent-context files from repository analysis.
// Commands: (default) generate | check | github <url>. Zero runtime dependencies.

import { readFileSync, writeFileSync, existsSync, mkdirSync, realpathSync } from "node:fs";
import { resolve, join, dirname, basename } from "node:path";
import { pathToFileURL } from "node:url";
import { scanDirectory } from "./vendor/cli/scanner.js";
import { fetchGitHubRepo } from "./vendor/snapshots/github.js";
import { analyzeFiles, stripGeneratedTargets, GENERATED_TARGET_PATHS, type RepoAnalysis } from "./pipeline.js";
import { selectTargets, type Target } from "./targets.js";
import { hasMarker } from "./marker.js";

export interface CliIO {
  out: (line: string) => void;
  err: (line: string) => void;
}

const DEFAULT_IO: CliIO = {
  out: (line) => console.log(line),
  err: (line) => console.error(line),
};

interface ParsedArgs {
  command: "generate" | "check" | "github" | "version" | "help";
  url?: string;
  dir?: string;
  out?: string;
  targets?: string;
  dryRun: boolean;
  force: boolean;
  quiet: boolean;
}

const HELP = `iliad — generate and maintain agent-context files from repository analysis

Usage:
  iliad [generate] [flags]     scan a repo and write agent-context files at its root
  iliad check [flags]          regenerate in memory, diff against disk, exit 1 on drift
  iliad github <url> [flags]   fetch a public GitHub repo and generate into --out

Targets (all by default):
  agents    AGENTS.md
  claude    CLAUDE.md
  cursor    .cursorrules
  copilot   .github/copilot-instructions.md
  gemini    GEMINI.md

Flags:
  --dir <path>        repository to scan (default: current directory)
  --out <dir>         output directory for github mode (default: ./iliad-output)
  --targets <list>    comma-separated subset of targets
  --dry-run           print what would be written without writing
  --force             overwrite files that lack the generated-by marker
  --quiet             suppress non-error output
  --version           print version
  --help              show this help

Safety: existing files WITHOUT the "generated by iliad" marker are never
overwritten unless --force is passed (protects hand-written files).`;

export function getVersion(): string {
  // new URL resolution works from both src/ (tsx/vitest) and dist/ layouts —
  // package.json sits one level above either directory.
  const pkg = JSON.parse(
    readFileSync(new URL("../package.json", import.meta.url), "utf-8"),
  ) as { version: string };
  return pkg.version;
}

function parseArgs(argv: string[]): ParsedArgs {
  const args: ParsedArgs = { command: "generate", dryRun: false, force: false, quiet: false };
  let i = 0;

  if (argv[0] && !argv[0].startsWith("-")) {
    const cmd = argv[0];
    if (cmd === "generate") {
      args.command = "generate";
      i = 1;
    } else if (cmd === "check") {
      args.command = "check";
      i = 1;
    } else if (cmd === "github") {
      args.command = "github";
      if (!argv[1] || argv[1].startsWith("-")) {
        throw new Error("github mode requires a repository URL: iliad github <url>");
      }
      args.url = argv[1];
      i = 2;
    } else {
      throw new Error(`Unknown command "${cmd}". Run iliad --help for usage.`);
    }
  }

  for (; i < argv.length; i++) {
    const a = argv[i];
    switch (a) {
      case "--dir":
        args.dir = requireValue(argv, ++i, "--dir");
        break;
      case "--out":
        args.out = requireValue(argv, ++i, "--out");
        break;
      case "--targets":
        args.targets = requireValue(argv, ++i, "--targets");
        break;
      case "--dry-run":
        args.dryRun = true;
        break;
      case "--force":
        args.force = true;
        break;
      case "--quiet":
        args.quiet = true;
        break;
      case "--version":
      case "-v":
        args.command = "version";
        break;
      case "--help":
      case "-h":
        args.command = "help";
        break;
      default:
        throw new Error(`Unknown flag "${a}". Run iliad --help for usage.`);
    }
  }
  return args;
}

function requireValue(argv: string[], idx: number, flag: string): string {
  const value = argv[idx];
  if (value === undefined || value.startsWith("-")) {
    throw new Error(`${flag} requires a value`);
  }
  return value;
}

interface WriteOptions {
  dryRun: boolean;
  force: boolean;
}

/**
 * Normalize CRLF → LF before comparing generated content against what is on
 * disk. On Windows, git core.autocrlf=true (a common installer default) or a
 * .gitattributes eol policy checks files out with CRLF endings; without this,
 * `check` reports permanent false drift and `generate` rewrites identical
 * files. Content comparison is EOL-insensitive; written bytes stay LF.
 */
function normalizeEol(s: string): string {
  return s.replace(/\r\n/g, "\n");
}

/** Write targets under baseDir, honoring marker protection. Returns counts. */
function writeTargets(
  baseDir: string,
  targets: Target[],
  analysis: RepoAnalysis,
  opts: WriteOptions,
  io: CliIO,
): { wrote: number; skipped: number; unchanged: number } {
  let wrote = 0;
  let skipped = 0;
  let unchanged = 0;

  for (const target of targets) {
    const content = target.emit(analysis);
    const outPath = join(baseDir, target.relPath);

    if (opts.dryRun) {
      io.out(`[dry-run] would write ${target.relPath} (${Buffer.byteLength(content, "utf-8")} bytes)`);
      continue;
    }

    if (existsSync(outPath)) {
      const existing = readFileSync(outPath, "utf-8");
      if (!hasMarker(existing) && !opts.force) {
        io.err(
          `warning: skipping ${target.relPath} — existing file has no iliad marker (looks hand-written); pass --force to overwrite`,
        );
        skipped++;
        continue;
      }
      if (normalizeEol(existing) === normalizeEol(content)) {
        io.out(`unchanged ${target.relPath}`);
        unchanged++;
        continue;
      }
    }

    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, content, "utf-8");
    io.out(`wrote ${target.relPath}`);
    wrote++;
  }

  return { wrote, skipped, unchanged };
}

function runGenerate(root: string, targets: Target[], opts: WriteOptions, io: CliIO): number {
  // Exclude our own outputs at scan time so they never consume MAX_FILES
  // slots; stripGeneratedTargets stays as defense-in-depth (and covers the
  // github path, which fetches files without going through the scanner).
  const scan = scanDirectory(root, { excludePaths: GENERATED_TARGET_PATHS });
  const files = stripGeneratedTargets(scan.files);
  const analysis = analyzeFiles(files, basename(root));
  const result = writeTargets(root, targets, analysis, opts, io);
  if (!opts.dryRun) {
    io.out(
      `done: ${result.wrote} written, ${result.unchanged} unchanged, ${result.skipped} skipped (${files.length} files analyzed)`,
    );
  }
  return 0;
}

function runCheck(root: string, targets: Target[], io: CliIO): number {
  const scan = scanDirectory(root, { excludePaths: GENERATED_TARGET_PATHS });
  const files = stripGeneratedTargets(scan.files);
  const analysis = analyzeFiles(files, basename(root));

  let drift = 0;
  for (const target of targets) {
    const expected = target.emit(analysis);
    const outPath = join(root, target.relPath);
    if (!existsSync(outPath)) {
      io.out(`missing  ${target.relPath}`);
      drift++;
      continue;
    }
    const onDisk = readFileSync(outPath, "utf-8");
    if (normalizeEol(onDisk) !== normalizeEol(expected)) {
      io.out(`drift    ${target.relPath}`);
      drift++;
    } else {
      io.out(`ok       ${target.relPath}`);
    }
  }

  if (drift > 0) {
    io.err(`${drift} file(s) missing or out of date — run npx iliad-md to refresh`);
    return 1;
  }
  io.out("all agent-context files are up to date");
  return 0;
}

async function runGithub(
  url: string,
  outDir: string,
  targets: Target[],
  opts: WriteOptions,
  io: CliIO,
): Promise<number> {
  io.out(`fetching ${url} ...`);
  const fetched = await fetchGitHubRepo(url);
  const files = stripGeneratedTargets(fetched.files);
  io.out(`fetched ${fetched.owner}/${fetched.repo}@${fetched.ref}: ${files.length} files`);
  const analysis = analyzeFiles(files, fetched.repo);
  if (!opts.dryRun) mkdirSync(outDir, { recursive: true });
  const result = writeTargets(outDir, targets, analysis, opts, io);
  if (!opts.dryRun) {
    io.out(`done: ${result.wrote} written, ${result.unchanged} unchanged, ${result.skipped} skipped → ${outDir}`);
  }
  return 0;
}

export async function runCli(argv: string[], io: CliIO = DEFAULT_IO): Promise<number> {
  let args: ParsedArgs;
  try {
    args = parseArgs(argv);
  } catch (e) {
    io.err(`error: ${e instanceof Error ? e.message : String(e)}`);
    return 1;
  }

  if (args.command === "help") {
    io.out(HELP);
    return 0;
  }
  if (args.command === "version") {
    io.out(getVersion());
    return 0;
  }

  const effectiveIO: CliIO = args.quiet ? { out: () => {}, err: io.err } : io;
  const writeOpts: WriteOptions = { dryRun: args.dryRun, force: args.force };

  try {
    const targets = selectTargets(args.targets);

    if (args.command === "github") {
      const outDir = resolve(args.dir ?? process.cwd(), args.out ?? "iliad-output");
      // args.url is guaranteed by parseArgs for the github command
      return await runGithub(args.url as string, outDir, targets, writeOpts, effectiveIO);
    }

    const root = resolve(args.dir ?? process.cwd());
    if (args.command === "check") {
      return runCheck(root, targets, effectiveIO);
    }
    return runGenerate(root, targets, writeOpts, effectiveIO);
  } catch (e) {
    io.err(`error: ${e instanceof Error ? e.message : String(e)}`);
    return 1;
  }
}

// ─── entry point ─────────────────────────────────────────────

function isDirectInvocation(): boolean {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return pathToFileURL(realpathSync(entry)).href === import.meta.url;
  } catch {
    return false;
  }
}

if (isDirectInvocation()) {
  runCli(process.argv.slice(2)).then((code) => {
    process.exitCode = code;
  }).catch((e: unknown) => {
    DEFAULT_IO.err(`error: ${e instanceof Error ? e.message : String(e)}`);
    process.exitCode = 1;
  });
}
