/** Marker lines that identify a file as generated by iliad. */

/** First line of every generated markdown target. */
export const MARKDOWN_MARKER =
  "<!-- generated by iliad — do not edit by hand; run npx iliad-md to refresh -->";

/** First line of .cursorrules (not markdown, so a # comment instead). */
export const HASH_MARKER =
  "# generated by iliad — do not edit by hand; run npx iliad-md to refresh";

/** True when the file content carries an iliad marker (safe to overwrite). */
export function hasMarker(content: string): boolean {
  return content.includes("generated by iliad");
}

/**
 * Join emitted lines into the final file content:
 * collapse runs of blank lines and end with exactly one trailing newline.
 * Keeps output byte-deterministic regardless of which sections were emitted.
 */
export function finalize(lines: string[]): string {
  return lines.join("\n").replace(/\n{3,}/g, "\n\n").replace(/\n*$/, "\n");
}
