// ─── E5 Living Architecture: drift webhook endpoint ─────────────
//
// POST endpoint that, on a verified GitHub push to the default branch,
// re-derives the verified living-architecture.md and opens a PR if it has
// drifted from the repo's committed copy. The baseline is the repo's OWN
// .axis/living-architecture.md (stateless — no per-repo store needed).
//
// processArchitectureDrift is pure orchestration over injected deps so it's
// testable without GitHub / a model; the handler does HTTP plumbing + wires the
// real implementations.

import type { IncomingMessage, ServerResponse } from "node:http";
import { readBody, sendJSON } from "./router.js";
import { verifyGitHubWebhookSignature, parsePushEvent, diffArchitecture, type PushInfo, type DriftResult } from "./architecture-drift.js";
import { openDriftPullRequest, driftBranchName, type OpenDriftPrParams, type OpenDriftPrResult } from "./github-pr.js";
import { runSpecificityPass } from "./living-architecture.js";
import { runCompletion } from "./llm-inference.js";
import { createSnapshot, extractSymbols, fetchGitHubRepo } from "@axis/snapshots";
import type { SnapshotManifest, InputMethod, FileEntry } from "@axis/snapshots";
import { buildContextMap } from "@axis/context-engine";

const ARTIFACT_PATH = ".axis/living-architecture.md";

// Best-effort per-process replay + concurrency guards. GitHub retries/replays
// deliveries and analysis is expensive (repo fetch + local model), so drop
// duplicate deliveries and concurrent same-repo jobs before doing the work.
const seenDeliveries = new Map<string, number>();
const inFlightRepos = new Set<string>();
const DELIVERY_TTL_MS = 15 * 60 * 1000;

function isDuplicateDelivery(deliveryId: string | undefined): boolean {
  if (!deliveryId) return false;
  const now = Date.now();
  for (const [id, ts] of seenDeliveries) {
    if (now - ts > DELIVERY_TTL_MS) seenDeliveries.delete(id);
  }
  if (seenDeliveries.has(deliveryId)) return true;
  seenDeliveries.set(deliveryId, now);
  return false;
}

export type DriftStatus = "no_token" | "model_not_configured" | "no_drift" | "pr_opened" | "pr_skipped";

export interface DriftOutcome {
  status: DriftStatus;
  drift?: DriftResult;
  pr?: OpenDriftPrResult;
}

export interface DriftDeps {
  token: string | undefined;
  fetchRepo: (url: string, token: string) => Promise<{ files: FileEntry[] }>;
  analyze: (files: FileEntry[]) => Promise<{ content: string; configured: boolean }>;
  openPr: (params: OpenDriftPrParams) => Promise<OpenDriftPrResult>;
}

function buildPrBody(drift: DriftResult): string {
  const lines = [
    "AXIS detected that this repository's architecture drifted from the committed `.axis/living-architecture.md`.",
    "Every claim in the update is grounded in a real repo fact (shown in parentheses) — ungrounded claims are dropped.",
    "",
  ];
  if (drift.added.length > 0) lines.push("**New / changed insights:**", ...drift.added.map((a) => `- ${a}`), "");
  if (drift.removed.length > 0) lines.push("**No longer accurate:**", ...drift.removed.map((r) => `- ${r}`), "");
  lines.push("— Generated by AXIS Living Architecture (engineer tier).");
  return lines.join("\n");
}

function splitRepo(fullName: string): { owner: string; repo: string } {
  const i = fullName.indexOf("/");
  return { owner: fullName.slice(0, i), repo: fullName.slice(i + 1) };
}

/**
 * Re-analyze a pushed repo and open a drift PR if the verified architecture doc
 * changed vs the repo's committed copy. Pure orchestration over injected deps.
 */
export async function processArchitectureDrift(push: PushInfo, deps: DriftDeps): Promise<DriftOutcome> {
  if (!deps.token) return { status: "no_token" };

  // Derive the fetch target from repo_full_name — the SAME field the PR is opened
  // against — so a crafted payload can't fetch repo A but write the PR to repo B.
  const fr = await deps.fetchRepo(`https://github.com/${push.repo_full_name}`, deps.token);
  const baseline = fr.files.find((f) => f.path === ARTIFACT_PATH)?.content ?? "";

  const analyzed = await deps.analyze(fr.files);
  if (!analyzed.configured) return { status: "model_not_configured" };

  const drift = diffArchitecture(baseline, analyzed.content);
  if (!drift.drifted) return { status: "no_drift", drift };

  const { owner, repo } = splitRepo(push.repo_full_name);
  const pr = await deps.openPr({
    owner,
    repo,
    token: deps.token,
    baseBranch: push.default_branch,
    filePath: ARTIFACT_PATH,
    content: analyzed.content,
    branchName: driftBranchName(analyzed.content),
    title: "AXIS: living architecture drift",
    body: buildPrBody(drift),
  });
  return { status: pr.opened ? "pr_opened" : "pr_skipped", drift, pr };
}

/** Real dependency wiring (GitHub fetch + headless analyze + PR creation). */
export function defaultDriftDeps(): DriftDeps {
  return {
    token: process.env.GITHUB_TOKEN,
    fetchRepo: (url, token) => fetchGitHubRepo(url, token),
    analyze: async (files) => {
      const manifest: SnapshotManifest = {
        project_name: "architecture-drift",
        project_type: "github_repository",
        frameworks: [],
        goals: ["Architecture drift check"],
        requested_outputs: [],
      };
      const snapshot = await createSnapshot({ input_method: "github_repo_url" as InputMethod, manifest, files }, undefined);
      const ctx = buildContextMap(snapshot);
      const symbols = extractSymbols(files);
      const art = await runSpecificityPass(ctx, symbols, runCompletion, { seed: 42 });
      return { content: art.content, configured: art.report.configured };
    },
    openPr: (params) => openDriftPullRequest(fetch, params),
  };
}

/**
 * POST /v1/github/architecture-drift — verify signature, ack fast, then process
 * asynchronously (GitHub expects a prompt response). 503 when the webhook secret
 * isn't configured (so GitHub retries), 401 on a bad signature.
 */
export async function handleArchitectureDriftWebhook(req: IncomingMessage, res: ServerResponse): Promise<void> {
  const secret = process.env.GITHUB_WEBHOOK_SECRET;
  if (!secret) {
    sendJSON(res, 503, { error: "architecture-drift webhook not configured", required_env: ["GITHUB_WEBHOOK_SECRET"] });
    return;
  }

  const rawBody = await readBody(req);
  const sigHeader = req.headers["x-hub-signature-256"];
  const sig = Array.isArray(sigHeader) ? sigHeader[0] : sigHeader;
  if (!verifyGitHubWebhookSignature(rawBody, sig, secret)) {
    sendJSON(res, 401, { error: "invalid webhook signature" });
    return;
  }

  const eventHeader = req.headers["x-github-event"];
  const event = Array.isArray(eventHeader) ? eventHeader[0] : eventHeader;
  if (event === "ping") {
    sendJSON(res, 200, { ok: true, pong: true });
    return;
  }
  if (event !== "push") {
    sendJSON(res, 202, { ignored: `event ${event ?? "unknown"}` });
    return;
  }

  let payload: unknown;
  try {
    payload = JSON.parse(rawBody);
  } catch {
    sendJSON(res, 400, { error: "invalid JSON body" });
    return;
  }

  const push = parsePushEvent(payload);
  if (!push) {
    sendJSON(res, 202, { ignored: "unparseable push event" });
    return;
  }
  if (!push.is_default_branch) {
    sendJSON(res, 202, { ignored: `non-default branch ${push.branch}` });
    return;
  }

  // Replay + concurrency guards before the expensive async work.
  const deliveryHeader = req.headers["x-github-delivery"];
  const deliveryId = Array.isArray(deliveryHeader) ? deliveryHeader[0] : deliveryHeader;
  if (isDuplicateDelivery(deliveryId)) {
    sendJSON(res, 202, { ignored: "duplicate delivery" });
    return;
  }
  if (inFlightRepos.has(push.repo_full_name)) {
    sendJSON(res, 202, { ignored: "drift job already running for this repo" });
    return;
  }

  // Ack now; the analysis + PR can take seconds (repo fetch + local model + GitHub
  // calls), and GitHub wants a fast response.
  sendJSON(res, 202, { accepted: true, repo: push.repo_full_name });
  inFlightRepos.add(push.repo_full_name);
  void processArchitectureDrift(push, defaultDriftDeps())
    .catch((err) => {
      console.error("architecture-drift processing failed:", err instanceof Error ? err.message : err);
    })
    .finally(() => {
      inFlightRepos.delete(push.repo_full_name);
    });
}
