// ─── app_24_canvas_rendered_diagrams: canvas program's Watch → Apply loop ──
//
// On every push for a "canvas"-subscribed repo, regenerates the real
// architecture diagram (generateArchitectureDiagram — real cross-directory
// import edges, never fabricated) and, if it changed, renders it to SVG via
// the real D2 binary (https://d2lang.com, MPL-2.0, a single Go binary — no
// headless Chromium, unlike Mermaid) and opens a PR with both the .d2 source
// and the rendered .svg.
//
// Safety note (why this is unlike app_10's "never execute server-side"
// stance): D2 is a declarative diagram DSL, not a general-purpose scripting
// language, and its input here is 100% AXIS-generated deterministic text
// derived from repo facts (never the user's own arbitrary file content) —
// there is no arbitrary-code-execution surface to worry about the way there
// would be running a user's own build/test commands. Rendering it
// server-side is safe.

import { spawnSync } from "node:child_process";
import { writeFileSync, readFileSync, mkdtempSync, rmSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fetchGitHubRepo, createSnapshot } from "@axis/snapshots";
import type { SnapshotManifest, FileEntry, WatchJobPayload } from "@axis/snapshots";
import { buildContextMap, buildRepoProfile } from "@axis/context-engine";
import { generateArchitectureDiagram } from "@axis/generator-core";
import { openApplyPullRequest, applyBranchName, type ApplyFile, type OpenApplyPrParams, type OpenApplyPrResult } from "./github-pr.js";

const CANVAS_PRODUCT_ID = "canvas";
export const DIAGRAM_D2_PATH = "docs/architecture-diagram.d2";
export const DIAGRAM_SVG_PATH = "docs/architecture-diagram.svg";

export type RenderD2Result = { ok: true; svg: string } | { ok: false; error: string };

export interface CanvasDiagramSyncDeps {
  token: string | undefined;
  fetchRepo: (url: string, token: string) => Promise<{ files: FileEntry[] }>;
  renderD2: (d2Source: string) => RenderD2Result;
  openPr: (params: OpenApplyPrParams) => Promise<OpenApplyPrResult>;
}

export type CanvasDiagramSyncStatus = "not_canvas_product" | "no_token" | "no_changes" | "render_failed" | "pr_opened" | "pr_skipped";

export interface CanvasDiagramSyncResult {
  status: CanvasDiagramSyncStatus;
  render_error?: string;
  pr?: OpenApplyPrResult;
}

function branchFromRef(ref: string): string {
  return ref.replace(/^refs\/heads\//, "") || "main";
}

function splitRepo(fullName: string): { owner: string; repo: string } {
  const i = fullName.indexOf("/");
  return { owner: fullName.slice(0, i), repo: fullName.slice(i + 1) };
}

function buildPrBody(): string {
  return [
    "AXIS detected that this repository's real inter-module dependency structure changed.",
    "",
    `Every edge in \`${DIAGRAM_D2_PATH}\` comes from an actual cross-directory import detected in this repo — nothing fabricated.`,
    "",
    `- \`${DIAGRAM_D2_PATH}\` — diagram source, editable with the [D2 CLI](https://d2lang.com)`,
    `- \`${DIAGRAM_SVG_PATH}\` — rendered diagram, embed with \`![Architecture](${DIAGRAM_SVG_PATH})\``,
    "",
    "— Generated by AXIS Canvas (watch mechanic).",
  ].join("\n");
}

/** Re-derives the architecture diagram for a pushed repo and opens a PR if it actually changed. Pure orchestration over injected deps so it's testable without GitHub or a real D2 binary. */
export async function processCanvasDiagramSync(payload: WatchJobPayload, deps: CanvasDiagramSyncDeps): Promise<CanvasDiagramSyncResult> {
  if (payload.product_id !== CANVAS_PRODUCT_ID) return { status: "not_canvas_product" };
  if (!deps.token) return { status: "no_token" };

  const fr = await deps.fetchRepo(`https://github.com/${payload.repo_full_name}`, deps.token);
  // Exclude the diagram's own prior output from what feeds its regeneration —
  // same lesson as app_11's skills-refresh-watcher: a previously-committed
  // artifact shouldn't influence its own next computation.
  const sourceFiles = fr.files.filter((f) => f.path !== DIAGRAM_D2_PATH && f.path !== DIAGRAM_SVG_PATH);

  const manifest: SnapshotManifest = {
    project_name: payload.repo_full_name,
    project_type: "github_repository",
    frameworks: [],
    goals: ["Redraw the architecture diagram"],
    requested_outputs: [],
  };
  // undefined account_id: this snapshot is transient (just to build ctx for
  // this one regeneration), never looked up again by account — unlike
  // mcp-hosted.ts's, which persists its snapshot as a subscription's
  // long-lived latest_snapshot_id and genuinely needs the FK link.
  const snapshot = await createSnapshot({ input_method: "github_repo_url", manifest, files: sourceFiles }, undefined);
  const ctx = buildContextMap(snapshot);
  const profile = buildRepoProfile(snapshot);
  const newD2Source = generateArchitectureDiagram(ctx, profile, sourceFiles).content;

  const existingD2Source = fr.files.find((f) => f.path === DIAGRAM_D2_PATH)?.content ?? "";
  if (newD2Source === existingD2Source) return { status: "no_changes" };

  const rendered = deps.renderD2(newD2Source);
  if (!rendered.ok) return { status: "render_failed", render_error: rendered.error };

  const { owner, repo } = splitRepo(payload.repo_full_name);
  const files: ApplyFile[] = [
    { path: DIAGRAM_D2_PATH, content: newD2Source },
    { path: DIAGRAM_SVG_PATH, content: rendered.svg },
  ];
  const pr = await deps.openPr({
    owner,
    repo,
    token: deps.token,
    baseBranch: branchFromRef(payload.ref),
    branchName: applyBranchName("canvas-diagram", newD2Source),
    files,
    title: "AXIS: redraw architecture diagram",
    body: buildPrBody(),
  });
  return { status: pr.opened ? "pr_opened" : "pr_skipped", pr };
}

const D2_TIMEOUT_MS = 30_000;

/** Real D2 CLI invocation — writes the source to a temp file, renders to SVG, reads it back. Bounded by a hard timeout: spawnSync blocks synchronously (see release-operator.ts's own header for why that matters), so a stuck render can never hang the watch worker indefinitely. */
export function realRenderD2(d2Source: string): RenderD2Result {
  const dir = mkdtempSync(join(tmpdir(), "axis-d2-"));
  try {
    const inputPath = join(dir, "diagram.d2");
    const outputPath = join(dir, "diagram.svg");
    writeFileSync(inputPath, d2Source, "utf-8");

    const r = spawnSync("d2", [inputPath, outputPath], {
      encoding: "utf-8",
      shell: process.platform === "win32",
      stdio: ["ignore", "pipe", "pipe"],
      timeout: D2_TIMEOUT_MS,
    });
    if (r.status !== 0 || !existsSync(outputPath)) {
      return { ok: false, error: `${r.stdout ?? ""}${r.stderr ?? ""}${r.error ? r.error.message : ""}` };
    }
    return { ok: true, svg: readFileSync(outputPath, "utf-8") };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/** Real dependency wiring (GitHub fetch + real D2 binary + Apply-channel PR creation). */
export function defaultCanvasDiagramSyncDeps(): CanvasDiagramSyncDeps {
  return {
    token: process.env.GITHUB_TOKEN,
    fetchRepo: (url, token) => fetchGitHubRepo(url, token),
    renderD2: realRenderD2,
    openPr: (params) => openApplyPullRequest(fetch, params),
  };
}
