// ─── E9 Commerce Integration: engineer-tier deployable bundle ────
//
// prepare_agentic_purchasing's engineer mode turns the descriptive compliance
// kit into a WORKING integration: it generates code the CUSTOMER deploys to
// their own infra, wired to their OWN PAI'D account. AXIS never sees or settles
// funds — it only emits artifacts. Everything here is a pure, deterministic
// function of (ContextMap, CommerceSignals) — no clock, no randomness — so the
// engineer bundle is reproducible and never enters the standard artifacts.

import type { ContextMap } from "@axis/context-engine";
import type { CommerceSignals } from "@axis/generator-core";

/**
 * Default price (in cents) stamped into the x402 endpoint AXIS generates FOR
 * THE CUSTOMER. This is the customer's own asking price on their own endpoint,
 * wired to their own PAI'D account -- it is NOT an AXIS price and must never be
 * sourced from @axis/mpp's PRICING_TIERS (that table prices AXIS's own tools).
 * $1.00 is a neutral, obviously-placeholder default the customer is expected to
 * change; it ships as `export const PRICE_CENTS` in their generated source, so
 * it is editable in one place on their side too. Named here rather than passed
 * as a bare literal at the call site so it is greppable and documented.
 */
export const GENERATED_ENDPOINT_DEFAULT_PRICE_CENTS = 100;

export interface CommerceArtifact {
  path: string;
  content: string;
  content_type: string;
}

export type Framework = "express" | "hono" | "node";

/** Pick the route binding to emit from the repo's detected frameworks. */
export function detectFramework(ctx: ContextMap): Framework {
  const names = ctx.detection.frameworks.map((f) => f.name.toLowerCase());
  if (names.some((n) => n.includes("hono"))) return "hono";
  if (names.some((n) => n.includes("express") || n.includes("next"))) return "express";
  return "node";
}

function frameworkBinding(framework: Framework): string[] {
  if (framework === "hono") {
    return [
      "// Hono binding — mount on your app: app.post('/purchase', x402Route)",
      "import type { Context } from \"hono\";",
      "export async function x402Route(c: Context) {",
      "  const headers = Object.fromEntries(c.req.raw.headers) as Record<string, string | undefined>;",
      "  const { status, body } = await handlePurchase(headers);",
      "  return c.json(body, status as 200 | 402);",
      "}",
    ];
  }
  if (framework === "express") {
    return [
      "// Express binding — mount on your app: app.post('/purchase', x402Route)",
      "import type { Request, Response } from \"express\";",
      "export async function x402Route(req: Request, res: Response) {",
      "  const { status, body } = await handlePurchase(req.headers as Record<string, string | undefined>);",
      "  res.status(status).json(body);",
      "}",
    ];
  }
  return [
    "// node:http binding — call from your request listener.",
    "import type { IncomingMessage, ServerResponse } from \"node:http\";",
    "export async function x402Route(req: IncomingMessage, res: ServerResponse) {",
    "  const { status, body } = await handlePurchase(req.headers as Record<string, string | undefined>);",
    "  res.writeHead(status, { \"Content-Type\": \"application/json\" });",
    "  res.end(JSON.stringify(body));",
    "}",
  ];
}

/**
 * Build the deployable x402 + AP2 + PAI'D endpoint. Written as an array of
 * literal lines so the generated code's own template literals / `${}` stay
 * verbatim. The core (challenge / mandate-verify / settle / orchestrate) is
 * framework-agnostic + injectable, so the generated test can exercise it.
 */
export function buildX402Endpoint(ctx: ContextMap, signals: CommerceSignals, priceCents: number): string {
  const framework = detectFramework(ctx);
  const provider = signals.detected_providers[0] ?? "paid";
  const lines: string[] = [
    "// x402-paid-endpoint.ts — generated by AXIS (engineer tier).",
    "// A deployable x402 + AP2 mandate + PAI'D settlement endpoint. Deploy this to",
    "// YOUR infrastructure; it settles to YOUR PAI'D account. AXIS never sees funds.",
    "// Configure via env (names only — never commit values):",
    "//   PAID_API_KEY, PAID_WEBHOOK_SECRET, AP2_MANDATE_SECRET",
    `// Detected framework: ${framework}. Detected provider signal: ${provider}.`,
    "import { createHmac, timingSafeEqual } from \"node:crypto\";",
    "",
    `export const PRICE_CENTS = ${Math.max(1, Math.round(priceCents))};`,
    "export const CURRENCY = \"usd\";",
    "",
    "// 1. x402 payment-required challenge (RFC 9457 + AP2 mandate constraints).",
    "export function createX402Challenge() {",
    "  return {",
    "    type: \"https://paymentauth.org/problems/payment-required\",",
    "    title: \"Payment Required\",",
    "    status: 402,",
    "    accepts: [{ scheme: \"paid\", amount_cents: PRICE_CENTS, currency: CURRENCY }],",
    "    ap2: { mandate_required: true, constraints: { max_amount_cents: PRICE_CENTS, currency: CURRENCY } },",
    "  };",
    "}",
    "",
    "// 2. AP2 mandate verification. The agent presents `<base64-payload>.<hex-hmac>`",
    "//    in X-AP2-Mandate. This scaffold verifies an HMAC over a shared secret;",
    "//    production should verify the agent's signature per the AP2 spec.",
    "export function verifyAp2Mandate(header: string | undefined, secret: string): { ok: boolean; amount_cents?: number } {",
    "  if (!header || !secret) return { ok: false };",
    "  const dot = header.lastIndexOf(\".\");",
    "  if (dot < 1) return { ok: false };",
    "  const payloadB64 = header.slice(0, dot);",
    "  const sig = header.slice(dot + 1);",
    "  const expected = createHmac(\"sha256\", secret).update(payloadB64).digest(\"hex\");",
    "  if (sig.length !== expected.length || !timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return { ok: false };",
    "  try {",
    "    const payload = JSON.parse(Buffer.from(payloadB64, \"base64\").toString(\"utf8\"));",
    "    const amt = Number(payload.max_amount_cents);",
    "    if (!Number.isFinite(amt) || amt < PRICE_CENTS) return { ok: false };",
    "    return { ok: true, amount_cents: amt };",
    "  } catch {",
    "    return { ok: false };",
    "  }",
    "}",
    "",
    "// 3. Settlement via YOUR PAI'D account.",
    "export async function settleViaPaid(reference: string, fetchImpl: typeof fetch = fetch) {",
    "  const key = process.env.PAID_API_KEY;",
    "  if (!key) throw new Error(\"PAID_API_KEY not configured\");",
    "  const res = await fetchImpl(\"https://api.paid.ai/v1/checkout/sessions\", {",
    "    method: \"POST\",",
    "    headers: { Authorization: `Bearer ${key}`, \"Content-Type\": \"application/json\" },",
    "    body: JSON.stringify({ amount_cents: PRICE_CENTS, currency: CURRENCY, reference }),",
    "  });",
    "  if (!res.ok) throw new Error(`PAID settlement failed (${res.status})`);",
    "  return res.json();",
    "}",
    "",
    "// 4. Orchestration (testable): no mandate -> 402; valid mandate -> settle.",
    "export interface PurchaseDeps { fetch?: typeof fetch }",
    "export async function handlePurchase(headers: Record<string, string | undefined>, deps: PurchaseDeps = {}) {",
    "  const fetchImpl = deps.fetch ?? fetch;",
    "  const mandate = verifyAp2Mandate(headers[\"x-ap2-mandate\"], process.env.AP2_MANDATE_SECRET ?? \"\");",
    "  if (!mandate.ok) return { status: 402 as const, body: createX402Challenge() };",
    "  // Per-purchase reference: prefer the caller's request id, else derive a",
    "  // stable-but-distinct id from the mandate (a constant would collapse distinct",
    "  // purchases if PAI'D treats reference as an idempotency key).",
    "  const reference = headers[\"x-request-id\"] ?? createHmac(\"sha256\", \"axis-ref\").update(headers[\"x-ap2-mandate\"] ?? \"\").digest(\"hex\").slice(0, 24);",
    "  const settlement = await settleViaPaid(reference, fetchImpl);",
    "  return { status: 200 as const, body: { settled: true, checkout: settlement } };",
    "}",
    "",
    ...frameworkBinding(framework),
    "",
  ];
  return lines.join("\n");
}

/**
 * Build a runnable vitest spec exercising the endpoint's mock 402 -> mandate ->
 * settle round-trip with an injected fetch (no live calls, no keys needed).
 */
export function buildX402EndpointTest(): string {
  const lines: string[] = [
    "// x402-endpoint.test.ts — generated by AXIS (engineer tier).",
    "// Run with: npx vitest run x402-endpoint.test.ts",
    "import { describe, it, expect, beforeEach } from \"vitest\";",
    "import { createHmac } from \"node:crypto\";",
    "import { createX402Challenge, verifyAp2Mandate, handlePurchase, PRICE_CENTS } from \"./x402-paid-endpoint\";",
    "",
    "const SECRET = \"test-mandate-secret\";",
    "function signMandate(payload: object, secret: string): string {",
    "  const b64 = Buffer.from(JSON.stringify(payload)).toString(\"base64\");",
    "  return b64 + \".\" + createHmac(\"sha256\", secret).update(b64).digest(\"hex\");",
    "}",
    "",
    "describe(\"x402 PAI'D endpoint\", () => {",
    "  beforeEach(() => {",
    "    process.env.AP2_MANDATE_SECRET = SECRET;",
    "    process.env.PAID_API_KEY = \"test-key\";",
    "  });",
    "",
    "  it(\"returns a 402 challenge when no mandate is presented\", async () => {",
    "    const r = await handlePurchase({});",
    "    expect(r.status).toBe(402);",
    "    expect(r.body.status).toBe(402);",
    "  });",
    "",
    "  it(\"settles a valid mandate via an injected PAI'D fetch\", async () => {",
    "    let called = false;",
    "    const fakeFetch = (async () => {",
    "      called = true;",
    "      return new Response(JSON.stringify({ checkout_url: \"https://paid.example/c/1\" }), { status: 200 });",
    "    }) as unknown as typeof fetch;",
    "    const mandate = signMandate({ max_amount_cents: PRICE_CENTS }, SECRET);",
    "    const r = await handlePurchase({ \"x-ap2-mandate\": mandate }, { fetch: fakeFetch });",
    "    expect(called).toBe(true);",
    "    expect(r.status).toBe(200);",
    "  });",
    "",
    "  it(\"rejects a tampered mandate\", async () => {",
    "    const bad = signMandate({ max_amount_cents: PRICE_CENTS }, \"wrong-secret\");",
    "    const r = await handlePurchase({ \"x-ap2-mandate\": bad });",
    "    expect(r.status).toBe(402);",
    "  });",
    "",
    "  it(\"emits a well-formed x402 challenge\", () => {",
    "    const c = createX402Challenge();",
    "    expect(c.status).toBe(402);",
    "    expect(c.ap2.mandate_required).toBe(true);",
    "    expect(c.accepts[0].amount_cents).toBe(PRICE_CENTS);",
    "  });",
    "});",
    "",
  ];
  return lines.join("\n");
}

// ─── Compelling Evidence 3.0 pack (field-complete + JSON Schema) ───

const FILL = "<FILL>";

/**
 * Build a submittable CE 3.0 evidence document + a JSON Schema that validates it.
 * Upgrades the standard kit's `<placeholder>` template into a concrete, schema-
 * validatable artifact for Visa dispute codes 10.2 / 10.3 / 10.4. Deterministic.
 */
export function buildCe3Evidence(signals: CommerceSignals, projectName: string): { json: string; schema: string } {
  const autoDerivable: string[] = [];
  if (signals.has_webhooks) autoDerivable.push("transaction timestamps (from webhook logs)");
  if (signals.has_network_tokenization) autoDerivable.push("payment_credential_id (network token)");
  if (signals.has_checkout) autoDerivable.push("shipping_address / account_id (checkout)");

  const txn = (note: string) => ({
    transaction_id: FILL,
    date: FILL,
    amount_cents: 0,
    currency: "usd",
    payment_credential_id: FILL,
    data_elements: { device_id: FILL, ip_address: FILL, shipping_address: FILL, account_id: FILL },
    _note: note,
  });

  const evidence = {
    compelling_evidence_version: "3.0",
    target_dispute_codes: ["10.2", "10.3", "10.4"],
    merchant: { name: projectName, mcc: FILL },
    disputed_transaction: txn("the transaction being disputed"),
    prior_undisputed_transactions: [
      txn("prior undisputed #1 — same payment credential as the disputed transaction"),
      txn("prior undisputed #2 — same payment credential"),
    ],
    matched_elements: ["device_id", "ip_address"],
    automation: {
      generated_by: "AXIS engineer tier (prepare_agentic_purchasing)",
      fields_auto_derivable: autoDerivable,
      requirement:
        "CE 3.0 needs >=2 prior undisputed transactions sharing the disputed payment credential, each matching >=2 data elements with the disputed transaction.",
    },
  };

  const txnSchema = {
    type: "object",
    required: ["transaction_id", "date", "amount_cents", "payment_credential_id", "data_elements"],
    properties: {
      transaction_id: { type: "string" },
      date: { type: "string" },
      amount_cents: { type: "integer", minimum: 0 },
      currency: { type: "string" },
      payment_credential_id: { type: "string" },
      data_elements: {
        type: "object",
        properties: {
          device_id: { type: "string" },
          ip_address: { type: "string" },
          shipping_address: { type: "string" },
          account_id: { type: "string" },
        },
      },
    },
  };

  const schema = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    title: "Compelling Evidence 3.0 submission",
    type: "object",
    required: ["compelling_evidence_version", "target_dispute_codes", "merchant", "disputed_transaction", "prior_undisputed_transactions", "matched_elements"],
    properties: {
      compelling_evidence_version: { const: "3.0" },
      target_dispute_codes: { type: "array", items: { enum: ["10.2", "10.3", "10.4"] } },
      merchant: { type: "object", required: ["name"], properties: { name: { type: "string" }, mcc: { type: "string" } } },
      disputed_transaction: { $ref: "#/$defs/txn" },
      prior_undisputed_transactions: { type: "array", minItems: 2, items: { $ref: "#/$defs/txn" } },
      matched_elements: {
        type: "array",
        minItems: 2,
        uniqueItems: true,
        items: { enum: ["device_id", "ip_address", "shipping_address", "account_id"] },
      },
    },
    $defs: { txn: txnSchema },
  };

  return { json: JSON.stringify(evidence, null, 2), schema: JSON.stringify(schema, null, 2) };
}

// ─── Transparent dispute-readiness score (NOT a win-rate prediction) ───

interface ReadinessDimension {
  key: string;
  label: string;
  present: boolean;
  remedy: string;
}

export interface DisputeReadiness {
  score: number;
  grade: string;
  dimensions: ReadinessDimension[];
  gaps: ReadinessDimension[];
  md: string;
}

/**
 * Score whether the caller can ASSEMBLE Compelling Evidence 3.0 — evidence-capture
 * readiness, NOT dispute-win odds (AXIS makes no outcome prediction). Each
 * dimension is a binary signal detected from the repo; score = present / total.
 */
export function buildDisputeReadiness(signals: CommerceSignals, projectName: string): DisputeReadiness {
  const dimensions: ReadinessDimension[] = [
    {
      key: "transaction_history",
      label: "Prior-transaction logging (>=2 undisputed transactions retrievable)",
      present: signals.has_webhooks || signals.has_dispute_handling,
      remedy: "Persist a webhook-driven transaction log so prior undisputed transactions can be retrieved.",
    },
    {
      key: "credential_matching",
      label: "Payment-credential matching across transactions",
      present: signals.has_network_tokenization || signals.has_mandate_management,
      remedy: "Store a stable payment-credential id (network token / mandate id) on every transaction.",
    },
    {
      key: "ip_capture",
      label: "Per-transaction IP address capture",
      present: signals.has_webhooks,
      remedy: "Record the client IP address on each transaction.",
    },
    {
      key: "address_account",
      label: "Shipping address / account id on record",
      present: signals.has_checkout,
      remedy: "Capture shipping address and account id at checkout.",
    },
    {
      key: "device_fingerprint",
      label: "Device id / fingerprint capture",
      present: false, // not detectable from source — always surfaced as a verify item
      remedy: "Add device fingerprinting (cannot be confirmed from code — verify manually).",
    },
    {
      key: "dispute_automation",
      label: "Dispute-evidence assembly automation",
      present: signals.has_dispute_handling,
      remedy: "Automate CE 3.0 pack assembly from your transaction store.",
    },
  ];

  const present = dimensions.filter((d) => d.present);
  const gaps = dimensions.filter((d) => !d.present);
  const score = Math.round((present.length / dimensions.length) * 100);
  const grade = score >= 85 ? "A" : score >= 70 ? "B" : score >= 50 ? "C" : "D";

  const md = [
    `# Dispute / CE 3.0 Readiness — ${projectName}`,
    "",
    "> A transparent measure of whether you can ASSEMBLE Compelling Evidence 3.0. It",
    "> scores evidence-capture readiness, NOT dispute-win odds — AXIS makes no",
    "> prediction about dispute outcomes.",
    "",
    `**Readiness: ${score}/100 (grade ${grade})** — ${present.length}/${dimensions.length} evidence dimensions in place.`,
    "",
    "## In place",
    ...(present.length > 0 ? present.map((d) => `- ${d.label}`) : ["- _(none yet)_"]),
    "",
    "## Gaps to close",
    ...(gaps.length > 0 ? gaps.map((d) => `- **${d.label}** — ${d.remedy}`) : ["- _(none — all evidence dimensions in place)_"]),
    "",
    "## How this is scored",
    "Each dimension is a binary signal detected from your repository; the score is",
    "dimensions-present / total. CE 3.0 requires >=2 prior undisputed transactions",
    "sharing the disputed payment credential, each matching >=2 data elements.",
    "",
  ].join("\n");

  return { score, grade, dimensions, gaps, md };
}

// ─── Stripe network-token adapter (WO-14 — E9 deployable artifact) ───

/**
 * Emit a deployable Stripe network-token read adapter, wired to the CUSTOMER's
 * own Stripe account (their STRIPE_SECRET_KEY — AXIS never sees it). Only
 * emitted when a Stripe signal is present; a repo with no Stripe integration
 * has no PaymentMethods to read. Returns null otherwise.
 *
 * Honesty is baked into the generated code: `is_network_token` maps STRICTLY
 * from `card.network_token.used === true` — co-badging metadata
 * (`card.networks.available`) is present on nearly every card PM and is NEVER
 * treated as a tokenization signal, so a bare card PM honestly reads false.
 */
export function emitStripeNetworkTokenAdapter(ctx: ContextMap, signals: CommerceSignals): CommerceArtifact | null {
  if (!signals.detected_providers.includes("stripe")) return null;
  const lines: string[] = [
    "// stripe-network-token-adapter.ts — generated by AXIS (engineer tier).",
    "// Reads YOUR Stripe PaymentMethods and maps them to a provider-agnostic",
    "// NetworkToken. Deploy to YOUR infrastructure; it uses YOUR Stripe account.",
    "// Configure via env (name only — never commit the value): STRIPE_SECRET_KEY",
    `// Generated for: ${ctx.project_identity.name}`,
    "//",
    "// HONESTY: is_network_token is true ONLY when Stripe reports a provisioned",
    "// network token (card.network_token.used === true). card.networks.available",
    "// is co-badging metadata — NOT a tokenization signal — and is ignored, so a",
    "// bare card PaymentMethod honestly reads false. Reading a real network token",
    "// requires Stripe's limited-access Network Tokens feature on your account.",
    "",
    "export interface NetworkToken {",
    "  token_ref: string;              // Stripe pm_… id — opaque, never a PAN",
    "  provider: \"stripe\";",
    "  is_network_token: boolean;      // true only when a real network token is present",
    "  network: string | null;         // card brand, e.g. \"visa\" | \"mastercard\"",
    "  last4: string | null;",
    "  token_state: \"active\";",
    "}",
    "",
    "export type FetchLike = (url: string, init?: RequestInit) => Promise<Response>;",
    "",
    "export async function readStripeNetworkToken(",
    "  paymentMethodId: string,",
    "  deps: { fetchImpl?: FetchLike; secretKey?: string } = {},",
    "): Promise<NetworkToken> {",
    "  const secretKey = deps.secretKey ?? process.env.STRIPE_SECRET_KEY;",
    "  if (!secretKey) throw new Error(\"STRIPE_SECRET_KEY not configured\");",
    "  const fetchImpl = deps.fetchImpl ?? fetch;",
    "  const res = await fetchImpl(`https://api.stripe.com/v1/payment_methods/${encodeURIComponent(paymentMethodId)}`, {",
    "    method: \"GET\",",
    "    headers: { Authorization: `Bearer ${secretKey}` },",
    "  });",
    "  if (!res.ok) throw new Error(`Stripe payment_methods read failed (${res.status})`);",
    "  const pm = (await res.json()) as { id?: string; card?: { brand?: string; last4?: string; network_token?: { used?: boolean } } };",
    "  return {",
    "    token_ref: pm.id ?? paymentMethodId,",
    "    provider: \"stripe\",",
    "    // STRICT mapping — card.network_token.used only (see header).",
    "    is_network_token: pm.card?.network_token?.used === true,",
    "    network: pm.card?.brand ?? null,",
    "    last4: pm.card?.last4 ?? null,",
    "    token_state: \"active\",",
    "  };",
    "}",
    "",
  ];
  return { path: "stripe-network-token-adapter.ts", content: lines.join("\n"), content_type: "text/typescript" };
}

/** Assemble the full engineer-mode commerce-integration bundle (5 core artifacts
 *  + the Stripe network-token adapter when a Stripe signal is present). */
export function buildCommerceIntegrationBundle(ctx: ContextMap, signals: CommerceSignals, priceCents: number): CommerceArtifact[] {
  const projectName = ctx.project_identity.name;
  const ce3 = buildCe3Evidence(signals, projectName);
  const readiness = buildDisputeReadiness(signals, projectName);
  const artifacts: CommerceArtifact[] = [
    { path: "x402-paid-endpoint.ts", content: buildX402Endpoint(ctx, signals, priceCents), content_type: "text/typescript" },
    { path: "x402-endpoint.test.ts", content: buildX402EndpointTest(), content_type: "text/typescript" },
    { path: "ce3-evidence.json", content: ce3.json, content_type: "application/json" },
    { path: "ce3-evidence.schema.json", content: ce3.schema, content_type: "application/json" },
    { path: "dispute-readiness.md", content: readiness.md, content_type: "text/markdown" },
  ];
  const tokenAdapter = emitStripeNetworkTokenAdapter(ctx, signals);
  if (tokenAdapter) artifacts.push(tokenAdapter);
  return artifacts;
}
