// ─── E9 Commerce Integration: engineer-tier deployable bundle ────
//
// prepare_agentic_purchasing's engineer mode turns the descriptive compliance
// kit into a WORKING integration: it generates code the CUSTOMER deploys to
// their own infra, wired to their OWN PAI'D account. AXIS never sees or settles
// funds — it only emits artifacts. Everything here is a pure, deterministic
// function of (ContextMap, CommerceSignals) — no clock, no randomness — so the
// engineer bundle is reproducible and never enters the standard artifacts.

import type { ContextMap } from "@axis/context-engine";
import type { CommerceSignals } from "@axis/generator-core";

export interface CommerceArtifact {
  path: string;
  content: string;
  content_type: string;
}

export type Framework = "express" | "hono" | "node";

/** Pick the route binding to emit from the repo's detected frameworks. */
export function detectFramework(ctx: ContextMap): Framework {
  const names = ctx.detection.frameworks.map((f) => f.name.toLowerCase());
  if (names.some((n) => n.includes("hono"))) return "hono";
  if (names.some((n) => n.includes("express") || n.includes("next"))) return "express";
  return "node";
}

function frameworkBinding(framework: Framework): string[] {
  if (framework === "hono") {
    return [
      "// Hono binding — mount on your app: app.post('/purchase', x402Route)",
      "import type { Context } from \"hono\";",
      "export async function x402Route(c: Context) {",
      "  const headers = Object.fromEntries(c.req.raw.headers) as Record<string, string | undefined>;",
      "  const { status, body } = await handlePurchase(headers);",
      "  return c.json(body, status as 200 | 402);",
      "}",
    ];
  }
  if (framework === "express") {
    return [
      "// Express binding — mount on your app: app.post('/purchase', x402Route)",
      "import type { Request, Response } from \"express\";",
      "export async function x402Route(req: Request, res: Response) {",
      "  const { status, body } = await handlePurchase(req.headers as Record<string, string | undefined>);",
      "  res.status(status).json(body);",
      "}",
    ];
  }
  return [
    "// node:http binding — call from your request listener.",
    "import type { IncomingMessage, ServerResponse } from \"node:http\";",
    "export async function x402Route(req: IncomingMessage, res: ServerResponse) {",
    "  const { status, body } = await handlePurchase(req.headers as Record<string, string | undefined>);",
    "  res.writeHead(status, { \"Content-Type\": \"application/json\" });",
    "  res.end(JSON.stringify(body));",
    "}",
  ];
}

/**
 * Build the deployable x402 + AP2 + PAI'D endpoint. Written as an array of
 * literal lines so the generated code's own template literals / `${}` stay
 * verbatim. The core (challenge / mandate-verify / settle / orchestrate) is
 * framework-agnostic + injectable, so the generated test can exercise it.
 */
export function buildX402Endpoint(ctx: ContextMap, signals: CommerceSignals, priceCents: number): string {
  const framework = detectFramework(ctx);
  const provider = signals.detected_providers[0] ?? "paid";
  const lines: string[] = [
    "// x402-paid-endpoint.ts — generated by AXIS (engineer tier).",
    "// A deployable x402 + AP2 mandate + PAI'D settlement endpoint. Deploy this to",
    "// YOUR infrastructure; it settles to YOUR PAI'D account. AXIS never sees funds.",
    "// Configure via env (names only — never commit values):",
    "//   PAID_API_KEY, PAID_WEBHOOK_SECRET, AP2_MANDATE_SECRET",
    `// Detected framework: ${framework}. Detected provider signal: ${provider}.`,
    "import { createHmac, timingSafeEqual } from \"node:crypto\";",
    "",
    `export const PRICE_CENTS = ${Math.max(1, Math.round(priceCents))};`,
    "export const CURRENCY = \"usd\";",
    "",
    "// 1. x402 payment-required challenge (RFC 9457 + AP2 mandate constraints).",
    "export function createX402Challenge() {",
    "  return {",
    "    type: \"https://paymentauth.org/problems/payment-required\",",
    "    title: \"Payment Required\",",
    "    status: 402,",
    "    accepts: [{ scheme: \"paid\", amount_cents: PRICE_CENTS, currency: CURRENCY }],",
    "    ap2: { mandate_required: true, constraints: { max_amount_cents: PRICE_CENTS, currency: CURRENCY } },",
    "  };",
    "}",
    "",
    "// 2. AP2 mandate verification. The agent presents `<base64-payload>.<hex-hmac>`",
    "//    in X-AP2-Mandate. This scaffold verifies an HMAC over a shared secret;",
    "//    production should verify the agent's signature per the AP2 spec.",
    "export function verifyAp2Mandate(header: string | undefined, secret: string): { ok: boolean; amount_cents?: number } {",
    "  if (!header || !secret) return { ok: false };",
    "  const dot = header.lastIndexOf(\".\");",
    "  if (dot < 1) return { ok: false };",
    "  const payloadB64 = header.slice(0, dot);",
    "  const sig = header.slice(dot + 1);",
    "  const expected = createHmac(\"sha256\", secret).update(payloadB64).digest(\"hex\");",
    "  if (sig.length !== expected.length || !timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return { ok: false };",
    "  try {",
    "    const payload = JSON.parse(Buffer.from(payloadB64, \"base64\").toString(\"utf8\"));",
    "    const amt = Number(payload.max_amount_cents);",
    "    if (!Number.isFinite(amt) || amt < PRICE_CENTS) return { ok: false };",
    "    return { ok: true, amount_cents: amt };",
    "  } catch {",
    "    return { ok: false };",
    "  }",
    "}",
    "",
    "// 3. Settlement via YOUR PAI'D account.",
    "export async function settleViaPaid(reference: string, fetchImpl: typeof fetch = fetch) {",
    "  const key = process.env.PAID_API_KEY;",
    "  if (!key) throw new Error(\"PAID_API_KEY not configured\");",
    "  const res = await fetchImpl(\"https://api.paid.ai/v1/checkout/sessions\", {",
    "    method: \"POST\",",
    "    headers: { Authorization: `Bearer ${key}`, \"Content-Type\": \"application/json\" },",
    "    body: JSON.stringify({ amount_cents: PRICE_CENTS, currency: CURRENCY, reference }),",
    "  });",
    "  if (!res.ok) throw new Error(`PAID settlement failed (${res.status})`);",
    "  return res.json();",
    "}",
    "",
    "// 4. Orchestration (testable): no mandate -> 402; valid mandate -> settle.",
    "export interface PurchaseDeps { fetch?: typeof fetch }",
    "export async function handlePurchase(headers: Record<string, string | undefined>, deps: PurchaseDeps = {}) {",
    "  const fetchImpl = deps.fetch ?? fetch;",
    "  const mandate = verifyAp2Mandate(headers[\"x-ap2-mandate\"], process.env.AP2_MANDATE_SECRET ?? \"\");",
    "  if (!mandate.ok) return { status: 402 as const, body: createX402Challenge() };",
    "  const settlement = await settleViaPaid(headers[\"x-request-id\"] ?? \"agent-purchase\", fetchImpl);",
    "  return { status: 200 as const, body: { settled: true, checkout: settlement } };",
    "}",
    "",
    ...frameworkBinding(framework),
    "",
  ];
  return lines.join("\n");
}

/**
 * Build a runnable vitest spec exercising the endpoint's mock 402 -> mandate ->
 * settle round-trip with an injected fetch (no live calls, no keys needed).
 */
export function buildX402EndpointTest(): string {
  const lines: string[] = [
    "// x402-endpoint.test.ts — generated by AXIS (engineer tier).",
    "// Run with: npx vitest run x402-endpoint.test.ts",
    "import { describe, it, expect, beforeEach } from \"vitest\";",
    "import { createHmac } from \"node:crypto\";",
    "import { createX402Challenge, verifyAp2Mandate, handlePurchase, PRICE_CENTS } from \"./x402-paid-endpoint\";",
    "",
    "const SECRET = \"test-mandate-secret\";",
    "function signMandate(payload: object, secret: string): string {",
    "  const b64 = Buffer.from(JSON.stringify(payload)).toString(\"base64\");",
    "  return b64 + \".\" + createHmac(\"sha256\", secret).update(b64).digest(\"hex\");",
    "}",
    "",
    "describe(\"x402 PAI'D endpoint\", () => {",
    "  beforeEach(() => {",
    "    process.env.AP2_MANDATE_SECRET = SECRET;",
    "    process.env.PAID_API_KEY = \"test-key\";",
    "  });",
    "",
    "  it(\"returns a 402 challenge when no mandate is presented\", async () => {",
    "    const r = await handlePurchase({});",
    "    expect(r.status).toBe(402);",
    "    expect(r.body.status).toBe(402);",
    "  });",
    "",
    "  it(\"settles a valid mandate via an injected PAI'D fetch\", async () => {",
    "    let called = false;",
    "    const fakeFetch = (async () => {",
    "      called = true;",
    "      return new Response(JSON.stringify({ checkout_url: \"https://paid.example/c/1\" }), { status: 200 });",
    "    }) as unknown as typeof fetch;",
    "    const mandate = signMandate({ max_amount_cents: PRICE_CENTS }, SECRET);",
    "    const r = await handlePurchase({ \"x-ap2-mandate\": mandate }, { fetch: fakeFetch });",
    "    expect(called).toBe(true);",
    "    expect(r.status).toBe(200);",
    "  });",
    "",
    "  it(\"rejects a tampered mandate\", async () => {",
    "    const bad = signMandate({ max_amount_cents: PRICE_CENTS }, \"wrong-secret\");",
    "    const r = await handlePurchase({ \"x-ap2-mandate\": bad });",
    "    expect(r.status).toBe(402);",
    "  });",
    "",
    "  it(\"emits a well-formed x402 challenge\", () => {",
    "    const c = createX402Challenge();",
    "    expect(c.status).toBe(402);",
    "    expect(c.ap2.mandate_required).toBe(true);",
    "    expect(c.accepts[0].amount_cents).toBe(PRICE_CENTS);",
    "  });",
    "});",
    "",
  ];
  return lines.join("\n");
}
