// ─── app_11_skills_never_rots: skills program's Watch → Apply loop ──
//
// The skills program's own generated CLAUDE.md ends every session with a
// promise most SaaS competitors can't make: the onboarding docs stay true as
// the codebase changes. This is what makes that promise real: consumes the
// watch queue (app_01 substrate) for "skills" subscriptions, and on a
// watched repo's push, re-derives AGENTS.md/CLAUDE.md/.cursorrules against
// the new tree. If any of the three actually changed, opens a refresh PR via
// the Apply-channel substrate (app_02); otherwise it's a silent no-op.
//
// No LLM involved — unlike E5 drift's LLM-compiled architecture doc, the
// skills generators are pure functions of the repo tree, so there's no
// "model not configured" gate to check. processSkillsRefresh mirrors
// architecture-drift-webhook.ts's injectable-deps shape closely (same
// fetch-repo → diff → open-PR skeleton), generalized to N files via
// openApplyPullRequest instead of the single-file drift adapter.

import { fetchGitHubRepo, createSnapshot, registerWatchWorker } from "@axis/snapshots";
import type { SnapshotManifest, FileEntry, WatchJobPayload } from "@axis/snapshots";
import { buildContextMap } from "@axis/context-engine";
import { generateAgentsMD, generateClaudeMD, generateCursorRules } from "@axis/generator-core";
import { openApplyPullRequest, applyBranchName, type ApplyFile, type OpenApplyPrParams, type OpenApplyPrResult } from "./github-pr.js";
import { log } from "./logger.js";

const SKILLS_PRODUCT_ID = "skills";

/** Paths this watcher itself manages — excluded from the file list fed to the
 *  generators (not from the "what's currently committed" diff target). Without
 *  this, a previously-committed AGENTS.md can itself skew stack/language
 *  detection (a large generated Markdown doc can outweigh a tiny real source
 *  tree) enough to change the NEXT regeneration's content — meaning the watch
 *  loop would never settle into a stable no-op and would keep opening PRs on
 *  every single push even with zero real code changes. Confirmed by generating
 *  twice: once from source alone, once from source + its own prior AGENTS.md
 *  output — the two runs detected different primary languages. */
const MANAGED_PATHS = new Set(["AGENTS.md", "CLAUDE.md", ".cursorrules"]);

const REFRESH_FILES: ReadonlyArray<{ path: string; generate: (ctx: ReturnType<typeof buildContextMap>, files?: FileEntry[]) => { content: string } }> = [
  { path: "AGENTS.md", generate: generateAgentsMD },
  { path: "CLAUDE.md", generate: generateClaudeMD },
  { path: ".cursorrules", generate: generateCursorRules },
];

export type SkillsRefreshStatus = "not_skills_product" | "no_token" | "no_changes" | "pr_opened" | "pr_skipped";

export interface SkillsRefreshOutcome {
  status: SkillsRefreshStatus;
  changed_paths?: string[];
  pr?: OpenApplyPrResult;
}

export interface SkillsRefreshDeps {
  token: string | undefined;
  fetchRepo: (url: string, token: string) => Promise<{ files: FileEntry[] }>;
  openPr: (params: OpenApplyPrParams) => Promise<OpenApplyPrResult>;
}

function branchFromRef(ref: string): string {
  return ref.replace(/^refs\/heads\//, "") || "main";
}

function splitRepo(fullName: string): { owner: string; repo: string } {
  const i = fullName.indexOf("/");
  return { owner: fullName.slice(0, i), repo: fullName.slice(i + 1) };
}

function buildPrBody(changed: ApplyFile[]): string {
  return [
    "AXIS detected that this repository's agent onboarding files no longer match what the current codebase supports.",
    "",
    "**Refreshed:**",
    ...changed.map((f) => `- \`${f.path}\``),
    "",
    "— Generated by AXIS Skills (watch mechanic).",
  ].join("\n");
}

/**
 * Re-derives the skills bundle for a pushed repo and opens a refresh PR if
 * any file actually changed vs the repo's committed copy. Pure orchestration
 * over injected deps so it's testable without GitHub.
 */
export async function processSkillsRefresh(payload: WatchJobPayload, deps: SkillsRefreshDeps): Promise<SkillsRefreshOutcome> {
  if (payload.product_id !== SKILLS_PRODUCT_ID) return { status: "not_skills_product" };
  if (!deps.token) return { status: "no_token" };

  const fr = await deps.fetchRepo(`https://github.com/${payload.repo_full_name}`, deps.token);
  const sourceFiles = fr.files.filter((f) => !MANAGED_PATHS.has(f.path));

  const manifest: SnapshotManifest = {
    project_name: payload.repo_full_name,
    project_type: "github_repository",
    frameworks: [],
    goals: ["Refresh agent onboarding files"],
    requested_outputs: [],
  };
  const snapshot = await createSnapshot({ input_method: "github_repo_url", manifest, files: sourceFiles }, undefined);
  const ctx = buildContextMap(snapshot);

  const changed: ApplyFile[] = [];
  for (const { path, generate } of REFRESH_FILES) {
    const generatedContent = generate(ctx, sourceFiles).content;
    const existingContent = fr.files.find((f) => f.path === path)?.content ?? "";
    if (generatedContent !== existingContent) {
      changed.push({ path, content: generatedContent });
    }
  }

  if (changed.length === 0) return { status: "no_changes" };

  const { owner, repo } = splitRepo(payload.repo_full_name);
  const branchSeed = changed.map((f) => `${f.path}:${f.content}`).join("\n");
  const pr = await deps.openPr({
    owner,
    repo,
    token: deps.token,
    baseBranch: branchFromRef(payload.ref),
    branchName: applyBranchName("skills-refresh", branchSeed),
    files: changed,
    title: "AXIS: refresh agent onboarding files",
    body: buildPrBody(changed),
  });
  return { status: pr.opened ? "pr_opened" : "pr_skipped", changed_paths: changed.map((f) => f.path), pr };
}

/** Real dependency wiring (GitHub fetch + Apply-channel PR creation). */
export function defaultSkillsRefreshDeps(): SkillsRefreshDeps {
  return {
    token: process.env.GITHUB_TOKEN,
    fetchRepo: (url, token) => fetchGitHubRepo(url, token),
    openPr: (params) => openApplyPullRequest(fetch, params),
  };
}

/** Registers this handler with the watch queue — call once at server startup. */
export async function startSkillsRefreshWatcher(): Promise<string> {
  return registerWatchWorker(async (payload) => {
    const outcome = await processSkillsRefresh(payload, defaultSkillsRefreshDeps());
    log("info", "skills-refresh.processed", {
      repo: payload.repo_full_name,
      product_id: payload.product_id,
      status: outcome.status,
    });
  });
}
