// ─── app_12_theme_token_sync: theme program's Watch → Apply loop ────
//
// AXIS's theme.css ships a fixed preset color palette as CSS custom
// properties (--color-<family>-<shade>) — a starting aesthetic to restyle,
// not something derived per-repo (see generators-theme.ts). "Drift" here is
// literal: a stylesheet hardcodes the EXACT hex value one of those variables
// already holds, instead of referencing the variable — e.g. `color: #06b6d4`
// instead of `color: var(--color-primary-500)`. On a "theme"-subscribed
// repo's push, this scans CSS/SCSS files for that exact literal drift and
// opens a PR that replaces it.
//
// The hex → variable-name map is derived by calling the REAL
// generateThemeCss and parsing its actual output, never hand-duplicated —
// this codebase's own harden-polish notes call out hand-duplicated
// catalog/pricing drift as a recurring bug family, and a hand-copied palette
// here would silently rot the moment generators-theme.ts's preset changes.
//
// Deliberately narrow: CSS/SCSS files only (var() is always valid there,
// unlike e.g. a JSX inline-style string where correctness depends on the
// surrounding syntax), and exact hex matches only (no fuzzy nearest-color
// matching, which risks "fixing" a color the user chose on purpose).

import { fetchGitHubRepo, createSnapshot } from "@axis/snapshots";
import type { SnapshotManifest, FileEntry, WatchJobPayload } from "@axis/snapshots";
import { buildContextMap } from "@axis/context-engine";
import { generateThemeCss } from "@axis/generator-core";
import { openApplyPullRequest, applyBranchName, type ApplyFile, type OpenApplyPrParams, type OpenApplyPrResult } from "./github-pr.js";

const THEME_PRODUCT_ID = "theme";
const CSS_FILE_PATTERN = /\.(css|scss)$/i;
/** AXIS's own generated file — never a drift target, it IS the source of truth. */
const GENERATED_THEME_CSS_PATH = "theme.css";

export type ThemeTokenSyncStatus = "not_theme_product" | "no_token" | "no_drift" | "pr_opened" | "pr_skipped";

export interface ThemeTokenSyncOutcome {
  status: ThemeTokenSyncStatus;
  changed_paths?: string[];
  pr?: OpenApplyPrResult;
}

export interface ThemeTokenSyncDeps {
  token: string | undefined;
  fetchRepo: (url: string, token: string) => Promise<{ files: FileEntry[] }>;
  openPr: (params: OpenApplyPrParams) => Promise<OpenApplyPrResult>;
}

/** Parses `--name: #hex;` custom-property declarations out of real generateThemeCss output. */
export function parseCssVariablePalette(themeCss: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const m of themeCss.matchAll(/(--[a-z0-9-]+):\s*(#[0-9a-fA-F]{3,8})\s*;/gi)) {
    map.set(m[2].toLowerCase(), m[1]);
  }
  return map;
}

/** Replaces every hex literal that exactly matches a known palette value with its var() reference. Case-insensitive on the hex; leaves anything not in the palette untouched. */
export function replaceKnownHexLiteralsWithVars(content: string, palette: Map<string, string>): { content: string; replacedCount: number } {
  let replacedCount = 0;
  const fixed = content.replace(/#[0-9a-fA-F]{3,8}\b/g, (hex) => {
    const varName = palette.get(hex.toLowerCase());
    if (!varName) return hex;
    replacedCount++;
    return `var(${varName})`;
  });
  return { content: fixed, replacedCount };
}

function splitRepo(fullName: string): { owner: string; repo: string } {
  const i = fullName.indexOf("/");
  return { owner: fullName.slice(0, i), repo: fullName.slice(i + 1) };
}

function buildPrBody(changed: ApplyFile[]): string {
  return [
    "AXIS detected hardcoded color values in this repo that exactly match colors already defined as design tokens.",
    "",
    "**Replaced with the matching CSS variable:**",
    ...changed.map((f) => `- \`${f.path}\``),
    "",
    "— Generated by AXIS Theme (watch mechanic).",
  ].join("\n");
}

function branchFromRef(ref: string): string {
  return ref.replace(/^refs\/heads\//, "") || "main";
}

/**
 * Detects exact hardcoded-hex drift against the real token palette and opens
 * a fix PR when found. Pure orchestration over injected deps.
 */
export async function processThemeTokenSync(payload: WatchJobPayload, deps: ThemeTokenSyncDeps): Promise<ThemeTokenSyncOutcome> {
  if (payload.product_id !== THEME_PRODUCT_ID) return { status: "not_theme_product" };
  if (!deps.token) return { status: "no_token" };

  const fr = await deps.fetchRepo(`https://github.com/${payload.repo_full_name}`, deps.token);

  const manifest: SnapshotManifest = {
    project_name: payload.repo_full_name,
    project_type: "github_repository",
    frameworks: [],
    goals: ["Detect theme token drift"],
    requested_outputs: [],
  };
  const snapshot = await createSnapshot({ input_method: "github_repo_url", manifest, files: fr.files }, undefined);
  const ctx = buildContextMap(snapshot);
  const palette = parseCssVariablePalette(generateThemeCss(ctx, fr.files).content);

  const changed: ApplyFile[] = [];
  for (const file of fr.files) {
    if (file.path === GENERATED_THEME_CSS_PATH || !CSS_FILE_PATTERN.test(file.path)) continue;
    const { content, replacedCount } = replaceKnownHexLiteralsWithVars(file.content, palette);
    if (replacedCount > 0) {
      changed.push({ path: file.path, content });
    }
  }

  if (changed.length === 0) return { status: "no_drift" };

  const { owner, repo } = splitRepo(payload.repo_full_name);
  const branchSeed = changed.map((f) => `${f.path}:${f.content}`).join("\n");
  const pr = await deps.openPr({
    owner,
    repo,
    token: deps.token,
    baseBranch: branchFromRef(payload.ref),
    branchName: applyBranchName("theme-token-sync", branchSeed),
    files: changed,
    title: "AXIS: sync hardcoded colors to design tokens",
    body: buildPrBody(changed),
  });
  return { status: pr.opened ? "pr_opened" : "pr_skipped", changed_paths: changed.map((f) => f.path), pr };
}

/** Real dependency wiring (GitHub fetch + Apply-channel PR creation). */
export function defaultThemeTokenSyncDeps(): ThemeTokenSyncDeps {
  return {
    token: process.env.GITHUB_TOKEN,
    fetchRepo: (url, token) => fetchGitHubRepo(url, token),
    openPr: (params) => openApplyPullRequest(fetch, params),
  };
}
