// ─── app_25_superpowers_executable: registry entries become dispatchable ──
// GitHub Actions jobs, not just prose to read. docs/saas-strategy/
// APPLICATION_BUILD_STRATEGY.md #12: "Accepts when: a registry entry can be
// run, not just read."
//
// Safety, matching this codebase's established local-only philosophy
// (app_10's verify-deploy, app_21's release-operator): the target repo's
// exec_steps are its OWN npm/pnpm/yarn scripts (install, build, test) —
// running them means real code executes, including postinstall hooks. That
// execution happens ONLY here, in the CLI, against the user's own machine —
// never inside AXIS's shared API process. Only after every exec_step passes
// locally does `axis verify-automations --execute` write the corresponding
// `.github/workflows/axis-automation-<id>.yml` file — a real workflow_dispatch
// job the user reviews and commits themselves, never auto-pushed.

import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { RunCmd } from "./release-operator.js";

export interface RegistryAutomation {
  id: string;
  name: string;
  category: string;
  trigger: string;
  steps: string[];
  exec_steps: string[] | null;
  applicable: boolean;
}

export interface AutomationStepResult {
  command: string;
  status: number | null;
  ok: boolean;
}

export interface AutomationVerifyResult {
  id: string;
  name: string;
  ok: boolean;
  steps: AutomationStepResult[];
  failed_command?: string;
  failure_output?: string;
}

/** Splits a generator-emitted command string into argv. These are always fixed literals or detected-package-manager names AXIS itself composed (see release-operator.ts's realRunCmd for the same reasoning) — never arbitrary user input — so a plain whitespace split is correct; none of these commands contain quoted arguments. */
function splitCommand(command: string): { cmd: string; args: string[] } {
  const [cmd, ...args] = command.trim().split(/\s+/);
  return { cmd, args };
}

/**
 * Actually runs an automation's exec_steps, in order, against a real repo —
 * stopping at the first failing step. This is what proves "runs green"
 * rather than merely "reads plausible."
 */
export function verifyAutomation(automation: RegistryAutomation, cwd: string, run: RunCmd): AutomationVerifyResult {
  const steps: AutomationStepResult[] = [];
  if (!automation.exec_steps || automation.exec_steps.length === 0) {
    return { id: automation.id, name: automation.name, ok: false, steps, failed_command: undefined, failure_output: "not machine-runnable (no exec_steps)" };
  }

  for (const command of automation.exec_steps) {
    const { cmd, args } = splitCommand(command);
    const result = run(cmd, args, cwd);
    const ok = result.status === 0;
    steps.push({ command, status: result.status, ok });
    if (!ok) {
      return {
        id: automation.id,
        name: automation.name,
        ok: false,
        steps,
        failed_command: command,
        failure_output: `${result.stdout}${result.stderr}`.slice(-4000),
      };
    }
  }

  return { id: automation.id, name: automation.name, ok: true, steps };
}

/** A single job's setup steps for the detected package manager — mirrors the corepack pattern already used across this repo's own .github/workflows/*.yml. */
function setupSteps(pkgMgr: string): string[] {
  const lines = [
    "      - uses: actions/checkout@v5",
    "      - uses: actions/setup-node@v5",
    "        with:",
    "          node-version: 22",
  ];
  if (pkgMgr === "pnpm") {
    lines.push("      - run: corepack enable && corepack prepare pnpm@10 --activate");
  } else if (pkgMgr === "yarn") {
    lines.push("      - run: corepack enable");
  }
  return lines;
}

/** Detects which package manager an exec_steps list already targets, so the emitted workflow's setup step matches (pnpm needs corepack; npm/yarn ship with actions/setup-node). */
function detectPkgMgr(execSteps: string[]): string {
  const joined = execSteps.join(" ");
  if (/\bpnpm\b/.test(joined)) return "pnpm";
  if (/\byarn\b/.test(joined)) return "yarn";
  return "npm";
}

/**
 * Emits a real GitHub Actions workflow, triggered only by workflow_dispatch
 * (never on push/PR — this is an on-demand automation, not a new CI gate),
 * running exactly the exec_steps that were just proven to pass locally.
 */
export function generateDispatchableWorkflowYaml(automation: RegistryAutomation): string {
  if (!automation.exec_steps || automation.exec_steps.length === 0) {
    throw new Error(`automation "${automation.id}" has no exec_steps — cannot emit a dispatchable workflow`);
  }
  const pkgMgr = detectPkgMgr(automation.exec_steps);
  const runLines = automation.exec_steps.map((step) => `      - run: ${step}`);
  return [
    `name: "AXIS Automation: ${automation.name}"`,
    "",
    "# Generated by axis-iliad's superpowers program (app_25_superpowers_executable).",
    `# Verified locally via "axis verify-automations --execute" before this file was written —`,
    "# every step below already ran green against this repo.",
    "",
    "on:",
    "  workflow_dispatch: {}",
    "",
    "jobs:",
    "  run:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    ...setupSteps(pkgMgr),
    ...runLines,
    "",
  ].join("\n");
}

/** Writes a verified automation's workflow file into <repoRoot>/.github/workflows/. Never commits or pushes — that stays a manual, reviewed step (same posture as release-operator.ts). */
export function writeDispatchableWorkflow(repoRoot: string, automation: RegistryAutomation): string {
  const dir = join(repoRoot, ".github", "workflows");
  mkdirSync(dir, { recursive: true });
  const filePath = join(dir, `axis-automation-${automation.id}.yml`);
  writeFileSync(filePath, generateDispatchableWorkflowYaml(automation), "utf-8");
  return filePath;
}
